using OneGood.Core.Enums;

namespace OneGood.Core.Models;

public class DailyAction
{
    public Guid Id { get; set; }
    public Guid CauseId { get; set; }
    public Cause Cause { get; set; } = null!;

    public ActionType Type { get; set; }
    public string Headline { get; set; } = string.Empty;
    public string CallToAction { get; set; } = string.Empty;
    public string WhyNow { get; set; } = string.Empty;
    public string WhyYou { get; set; } = string.Empty;
    public string ImpactStatement { get; set; } = string.Empty;

    // For donation actions
    public decimal? SuggestedAmount { get; set; }
    public string? StripePaymentLinkUrl { get; set; }

    // For letter/contact actions
    public string? PreWrittenLetter { get; set; }
    public string? RecipientName { get; set; }
    public string? RecipientEmail { get; set; }
    public string? RecipientTitle { get; set; }

    // For share actions
    public string? ShareText { get; set; }
    public string? ShareUrl { get; set; }

    /// <summary>
    /// True if this action's content (headline, whyNow, impact) was generated by AI.
    /// False if it's a fallback using original source data.
    /// </summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>
    /// Language code (e.g. "en", "de") for which this action's content was generated.
    /// </summary>
    public string Language { get; set; } = "en";

    public DateTime ValidFrom { get; set; }
    public DateTime ValidUntil { get; set; }
    public ActionStatus Status { get; set; }
    public int TimesCompleted { get; set; }
    public int TimesShown { get; set; }

    public ICollection<UserAction> UserActions { get; set; } = [];
    public Outcome? Outcome { get; set; }
}
