// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneGood.Infrastructure.Data;

#nullable disable

namespace OneGood.Infrastructure.Migrations
{
    [DbContext(typeof(OneGoodDbContext))]
    [Migration("20260504091716_AddUserProfileExtensions")]
    partial class AddUserProfileExtensions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneGood.Core.Models.AnalyticsEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionDetail")
                        .HasColumnType("text");

                    b.Property<string>("BrowserLanguage")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AnalyticsEvents");
                });

            modelBuilder.Entity("OneGood.Core.Models.Cause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionsToTippingPoint")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("FundingCurrent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("FundingGoal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LeverageScore")
                        .HasColumnType("double precision");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganisationUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceApiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UrgencyScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UrgencyScore");

                    b.ToTable("Causes");
                });

            modelBuilder.Entity("OneGood.Core.Models.CauseTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CauseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CauseId", "Language")
                        .IsUnique();

                    b.ToTable("CauseTranslations");
                });

            modelBuilder.Entity("OneGood.Core.Models.DailyAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallToAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CauseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactStatement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en");

                    b.Property<string>("PreWrittenLetter")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text");

                    b.Property<string>("RecipientTitle")
                        .HasColumnType("text");

                    b.Property<string>("ShareText")
                        .HasColumnType("text");

                    b.Property<string>("ShareUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripePaymentLinkUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("SuggestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TimesCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("TimesShown")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhyNow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyYou")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CauseId");

                    b.ToTable("DailyActions");
                });

            modelBuilder.Entity("OneGood.Core.Models.Outcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyActionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OutcomeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeopleImpacted")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalActionsContributed")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalDonationsRaised")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DailyActionId")
                        .IsUnique();

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("OneGood.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OneGood.Core.Models.UserAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AmountDonated")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DailyActionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SawOutcome")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DailyActionId");

                    b.HasIndex("UserId", "CompletedAt");

                    b.ToTable("UserActions");
                });

            modelBuilder.Entity("OneGood.Core.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionsCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("HasSavedPaymentMethod")
                        .HasColumnType("boolean");

                    b.Property<string>("InferredInterestsSummary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxDonationPerAction")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PreferredCategories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalDonated")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WillingToDonate")
                        .HasColumnType("boolean");

                    b.Property<bool>("WillingToShare")
                        .HasColumnType("boolean");

                    b.Property<bool>("WillingToWrite")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("OneGood.Core.Models.CauseTranslation", b =>
                {
                    b.HasOne("OneGood.Core.Models.Cause", "Cause")
                        .WithMany("Translations")
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cause");
                });

            modelBuilder.Entity("OneGood.Core.Models.DailyAction", b =>
                {
                    b.HasOne("OneGood.Core.Models.Cause", "Cause")
                        .WithMany("Actions")
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cause");
                });

            modelBuilder.Entity("OneGood.Core.Models.Outcome", b =>
                {
                    b.HasOne("OneGood.Core.Models.DailyAction", "DailyAction")
                        .WithOne("Outcome")
                        .HasForeignKey("OneGood.Core.Models.Outcome", "DailyActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyAction");
                });

            modelBuilder.Entity("OneGood.Core.Models.UserAction", b =>
                {
                    b.HasOne("OneGood.Core.Models.DailyAction", "DailyAction")
                        .WithMany("UserActions")
                        .HasForeignKey("DailyActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneGood.Core.Models.User", "User")
                        .WithMany("CompletedActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyAction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneGood.Core.Models.UserProfile", b =>
                {
                    b.HasOne("OneGood.Core.Models.User", null)
                        .WithOne("Profile")
                        .HasForeignKey("OneGood.Core.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneGood.Core.Models.Cause", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("OneGood.Core.Models.DailyAction", b =>
                {
                    b.Navigation("Outcome");

                    b.Navigation("UserActions");
                });

            modelBuilder.Entity("OneGood.Core.Models.User", b =>
                {
                    b.Navigation("CompletedActions");

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
